
BUCKET = 'temporal-natural-scenes-dataset'

SEED_FILES = ['dataset_description.json',
              'CITATION.cff',
              'LICENSE',
              'README.md',
              'CHANGES',
              'derivatives/V0/epochs/metadata.tsv',
              'derivatives/V1/epochs/metadata.tsv',
              'derivatives/V2/epochs/metadata.tsv',
              'derivatives/V3/epochs/metadata.tsv',
              'sub-01/sub-01_sessions.tsv',
              'sub-02/sub-02_sessions.tsv',
              'sub-03/sub-03_sessions.tsv',
              'sub-04/sub-04_sessions.tsv',
              'sub-05/sub-05_sessions.tsv',
              'sub-06/sub-06_sessions.tsv',
              'sub-07/sub-07_sessions.tsv',
              'sub-08/sub-08_sessions.tsv',
              'sub-09/sub-09_sessions.tsv',
              'sub-10/sub-10_sessions.tsv',
              'sub-11/sub-11_sessions.tsv',
              'sub-12/sub-12_sessions.tsv',
              'sub-13/sub-13_sessions.tsv',
              'sub-14/sub-14_sessions.tsv',
              'sub-15/sub-15_sessions.tsv',
              'sub-16/sub-16_sessions.tsv',
              'sub-17/sub-17_sessions.tsv',
              'sub-18/sub-18_sessions.tsv',
]